/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InformacionPaneles;

import OpcionesMenu.MenuInfo;
import menucoldware.FrameGeneral;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.SwingUtilities;

/**
 *
 * @author rasca
 */
public class InfoPlanetas extends javax.swing.JPanel implements ActionListener {
        String infoPlanetas;
        
   
    /**
     * 
     * Creates new form InfoPlanetas
     */
    public InfoPlanetas() {
        initComponents();
            
        
        
        
        
        
          Volver.addActionListener(this);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Volver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Volver.setText("Volver");
        add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 670, 102, 39));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Planeta Normal: 200 de vida 50 misiles. ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 227, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Planeta Rojo: 200 de vida 50 misiles Ataque efectivos contra planeta Verde(x2). Poco efectivos contra planeta Azul(/2).");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 701, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Planeta Azul: 200 de vida 50 misiles Ataque efectivos contra planeta Rojo(x2). Poco efectivos contra planeta Verde(/2)");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 701, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Planeta Verde: 200 de vida 50 misiles Ataque efectivos contra planeta Azul(x2). Poco efectivos contra planeta Rojo(/2).");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 701, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Planeta Gaseoso: 400 de vida 10 base + 10 misiles por ronda.");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 701, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Planeta Enano: 100 de vida 50 misiles  probabilidad de esquivar del 50%.");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 701, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Planeta Berserk: 100 de vida 150 misiles, no puede defenderse.");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 701, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Planeta Oscuro 200 de vida 50 misiles  Si el objetivo atacado tiene menos del 20% de vida dano x2.");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 701, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Planeta Vegeta Super Saiyan 2: 100 de vida, +100 de vida extra por planeta en la partida. 30 misiles, + 10 misiles extra por planeta en la partida.");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Planeta Nigromante 175 de vida 40 misiles  Cuando un equipo muere, se cura 40 puntos de vida y recibe ");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 701, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText(" +20de ataque en forma de un ‘planeta zombi’");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 670, 366, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("INFORMACION PLANETAS");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, 48));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/config_equips_.gif"))); // NOI18N
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource()==Volver){
        FrameGeneral marco=(FrameGeneral) SwingUtilities.getWindowAncestor(this);
	marco.remove(this);
	marco.add(new MenuInfo());
	marco.setVisible(true);
            
        }
        
        
        
    }
}
