/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InformacionPaneles;

import OpcionesMenu.MenuInfo;
import menucoldware.FrameGeneral;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.SwingUtilities;

/**
 *
 * @author rasca
 */
public class InfoJugar extends javax.swing.JPanel implements ActionListener{

    /**
     * Creates new form InfoJugar
     */
    public InfoJugar() {
        initComponents();
        Volver.addActionListener(this);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Volver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Volver.setText("Volver");
        add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 670, 92, 32));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Acerca de este programa");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 215, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Coldawar es un simulador estratégico de épicas batallas navales donde deberas ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 437, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("cambiar el rumbo de la batalla con tu propia audacia.");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 461, 14));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Derrotando a tus enemigos tomando decisiones arriesgadas y hazte con la victoria.");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 484, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tiene un modo Partida normal y un modo adicional para jugar individualmente para ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 472, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("comprobar tu astucia y paciencia. Al pasarse ese modo conseguiras gloriosas recomensas");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, 480, 19));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText(" pero no te será tan fácil …..");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, 450, 14));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/config_equips_.gif"))); // NOI18N
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Volver;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        
        if(e.getSource()==Volver){
        FrameGeneral marco=(FrameGeneral) SwingUtilities.getWindowAncestor(this);
	marco.remove(this);
	marco.add(new MenuInfo());
	marco.setVisible(true);
            
        }
        
        
        
    }
}
