/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ColdWar;

import OpcionesMenu.MenuModo;
import BossRush.Eleccion_Jugador;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import menucoldware.FrameGeneral;

/**
 *
 * @author Haru
 */
public class Pelea_ColdWar extends javax.swing.JPanel {

    ArrayList<Integer> ataque = new ArrayList<Integer>();

    String numero_missiles;
    int hp1 = 100;
    int hp2 = 100;
    int hp3 = 100;
    int hp4 = 100;
    int hp5 = 100;
    int hp6 = 100;
    int x;
    int equipo;
    boolean vivo1;
    boolean vivo2;
    boolean vivo3;
    boolean vivo4;
    boolean vivo5;
    boolean vivo6;

    int missiles;
    int missiles_totales = 30;
    int daño_equipo;
    int daño;
    String seleccion_equipo;
    Planeta guardarEquipo;
    int numero_de_equipo;
    
    public Pelea_ColdWar(String jugador1,String jugador2,String jugador3, String jugador4, String jugador5, String jugador6) {
        initComponents();
        
        nombre1.setText(jugador1);
        nombre2.setText(jugador2);
        nombre3.setText(jugador3);
        nombre4.setText(jugador4);
        nombre5.setText(jugador5);
        nombre6.setText(jugador6);
        
        

        vida1.setText(String.valueOf(hp1 + " HP"));
        vida2.setText(String.valueOf(hp2 + " HP"));
        vida3.setText(String.valueOf(hp3 + " HP"));
        vida4.setText(String.valueOf(hp4 + " HP"));
        vida5.setText(String.valueOf(hp5 + " HP"));
        vida6.setText(String.valueOf(hp6 + " HP"));

        count_missiles.setText(String.valueOf(missiles_totales + " missiles"));
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Log = new javax.swing.JTextArea();
        atacar = new javax.swing.JButton();
        equipos = new javax.swing.JComboBox<>();
        Nombre_equipo = new javax.swing.JLabel();
        nombre1 = new javax.swing.JTextField();
        nombre2 = new javax.swing.JTextField();
        nombre3 = new javax.swing.JTextField();
        nombre4 = new javax.swing.JTextField();
        nombre5 = new javax.swing.JTextField();
        nombre6 = new javax.swing.JTextField();
        vida1 = new javax.swing.JLabel();
        vida2 = new javax.swing.JLabel();
        vida3 = new javax.swing.JLabel();
        vida4 = new javax.swing.JLabel();
        vida5 = new javax.swing.JLabel();
        vida6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        numero_miss = new javax.swing.JTextField();
        count_missiles = new javax.swing.JLabel();
        Salir = new javax.swing.JButton();

        Log.setColumns(20);
        Log.setRows(5);
        jScrollPane1.setViewportView(Log);

        atacar.setText("Atacar");
        atacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atacarActionPerformed(evt);
            }
        });

        equipos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Equipo 1", "Equipo 2", "Equipo 3", "Equipo 4", "Equipo 5", "Equipo 6" }));
        equipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equiposActionPerformed(evt);
            }
        });

        Nombre_equipo.setText("Equipo 1 ");

        nombre1.setEditable(false);
        nombre1.setText("Equipo 1");

        nombre2.setEditable(false);
        nombre2.setText("Equipo 2");

        nombre3.setEditable(false);
        nombre3.setText("Equipo 3");

        nombre4.setEditable(false);
        nombre4.setText("Equipo 4");

        nombre5.setEditable(false);
        nombre5.setText("Equipo 5");

        nombre6.setEditable(false);
        nombre6.setText("Equipo 6");

        vida1.setText("HP 1");

        vida2.setText("HP 2");

        vida3.setText("Hp 3");

        vida4.setText("HP 4");

        vida5.setText("Hp 5");

        vida6.setText("HP 6");

        jButton1.setText("Defender");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        numero_miss.setText("Num miss");
        numero_miss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero_missActionPerformed(evt);
            }
        });

        count_missiles.setText("jLabel2");

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombre1)
                            .addComponent(nombre2)
                            .addComponent(nombre3, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(nombre4)
                            .addComponent(nombre5)
                            .addComponent(nombre6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(Nombre_equipo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(equipos, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(numero_miss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(atacar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(38, 38, 38)
                        .addComponent(count_missiles, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vida2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vida3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vida4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vida5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vida6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vida1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(111, 111, 111))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Salir)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(equipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nombre_equipo)
                            .addComponent(numero_miss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(atacar)
                            .addComponent(jButton1)
                            .addComponent(count_missiles))
                        .addGap(155, 155, 155)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vida1))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vida2))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombre3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vida3))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombre4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vida4))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombre5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vida5))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombre6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vida6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Salir))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(132, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void atacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atacarActionPerformed
        // TODO add your handling code here:
        
        String numero_de_missiles = "" + numero_miss.getText();

        missiles = Integer.parseInt(numero_de_missiles);
        missiles_totales = missiles_totales - missiles;

        String equipos_sel = (String) equipos.getSelectedItem();
        

        count_missiles.setText(String.valueOf(missiles_totales + " missiles"));
        
        numero_de_equipo = (Integer) equipos.getSelectedIndex() + 1;
        
        
        daño_equipo = missiles;
        
        if (missiles_totales <= 0 ) {
            
            if (missiles >= 31) {
                JOptionPane.showMessageDialog(this, "Introducce un numero menor de 30");
                missiles_totales = 0;
                
            } else if (missiles_totales <= 0 ) {
                JOptionPane.showMessageDialog(this, "Turno de otro Jugador ");
                Cambio_Equipo();
            }else if (missiles == 0){
                JOptionPane.showMessageDialog(this, "No puedes poner 0 puto mongolo de mierda ");
            }
            
            missiles_totales = 0;
            
        }
        if(equipo == 6){ 
            Comprobacion_Equipos();
       } 
        ataque.add(daño_equipo);
        System.out.println(ataque);   

    }//GEN-LAST:event_atacarActionPerformed

    public void Cambio_Equipo() { 
        
        
        if (numero_de_equipo == 1) {
            hp1 = hp1 - daño_equipo;
            vida1.setText(String.valueOf(hp1 + " HP"));

        } else if (numero_de_equipo == 2) {
            hp2 = hp2 - daño_equipo;
            vida2.setText(String.valueOf(hp2 + " HP"));
        } else if (numero_de_equipo == 3) {
            hp3 = hp3 - missiles;
            vida3.setText(String.valueOf(hp3 + " HP"));
        } else if (numero_de_equipo == 4) {
            hp4 = hp4 - missiles;
            vida4.setText(String.valueOf(hp4 + " HP"));
        } else if (numero_de_equipo == 5) {
            hp5 = hp5 - missiles;
            vida5.setText(String.valueOf(hp5 + " HP"));
        } else if (numero_de_equipo == 6) {
            hp6 = hp6 - missiles;
            vida6.setText(String.valueOf(hp6 + " HP"));
        }
        equipo++;

      
    }
    
    private void equiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equiposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_equiposActionPerformed

    private void numero_missActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero_missActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numero_missActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        missiles_totales = 0;
       

    }//GEN-LAST:event_jButton1ActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:

        FrameGeneral marco = (FrameGeneral) SwingUtilities.getWindowAncestor(this);
        marco.remove(this);
        marco.add(new MenuModo());
        marco.setVisible(true);


    }//GEN-LAST:event_SalirActionPerformed

    public void Comprobacion_Equipos(){
        
        if (hp1 <= 0 ){
           nombre1.setText("estas muerto");
 
        }
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Log;
    private javax.swing.JLabel Nombre_equipo;
    private javax.swing.JButton Salir;
    private javax.swing.JButton atacar;
    private javax.swing.JLabel count_missiles;
    private javax.swing.JComboBox<String> equipos;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombre1;
    private javax.swing.JTextField nombre2;
    private javax.swing.JTextField nombre3;
    private javax.swing.JTextField nombre4;
    private javax.swing.JTextField nombre5;
    private javax.swing.JTextField nombre6;
    private javax.swing.JTextField numero_miss;
    private javax.swing.JLabel vida1;
    private javax.swing.JLabel vida2;
    private javax.swing.JLabel vida3;
    private javax.swing.JLabel vida4;
    private javax.swing.JLabel vida5;
    private javax.swing.JLabel vida6;
    // End of variables declaration//GEN-END:variables
}
