/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OpcionesMenu;


import PartidaNormal.Partida;
import PartidaNormal.Planeta;
import PartidaNormal.connection;
import menucoldware.FrameGeneral;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.SwingUtilities;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author DAW2
 */
public class MenuPrincipal extends javax.swing.JPanel implements ActionListener {
    
    /**
     * Creates new form MenuJugar
     */
    int resultado;
    boolean cargar;
    ArrayList<Planeta> equipos = new ArrayList<Planeta>();
    int numeroEquipos;
    int x;
    
    public MenuPrincipal() {
        initComponents();
        
     
         Informacion.addActionListener(this);
         Jugar.addActionListener(this);
         Salir.addActionListener(this);
         CargarPartida.addActionListener(this);
         
         
         
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Jugar = new javax.swing.JButton();
        Informacion = new javax.swing.JButton();
        CargarPartida = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setToolTipText("");
        setFocusable(false);
        setPreferredSize(new java.awt.Dimension(700, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/titulilloColdware.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 440, 120));

        Jugar.setText("Start");
        Jugar.setFocusable(false);
        add(Jugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 200, 42));

        Informacion.setText("Información");
        Informacion.setFocusable(false);
        Informacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InformacionActionPerformed(evt);
            }
        });
        add(Informacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, 200, 42));

        CargarPartida.setText("Cargar Partida");
        CargarPartida.setFocusable(false);
        CargarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarPartidaActionPerformed(evt);
            }
        });
        add(CargarPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 430, 200, 38));

        Salir.setText("Salir");
        Salir.setFocusable(false);
        add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 530, 200, 46));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1003142_ediblefromage_oncoming-storm.gif"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1280, 760));
    }// </editor-fold>//GEN-END:initComponents

    private void CargarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarPartidaActionPerformed
        // TODO add your handling code here:
        
        
          String[] buttons = { "Si", "No"  };

        resultado = JOptionPane.showOptionDialog(null, "Quiere usted cargar la partida caballero?", "Confirmation",
        JOptionPane.WARNING_MESSAGE, 0, null, buttons, buttons[0]);

     if(resultado == 0){
        cargar = true;
        
        FrameGeneral marco=(FrameGeneral) SwingUtilities.getWindowAncestor(this);
	marco.remove(this);
	marco.add(new Partida(equipos, numeroEquipos,cargar));
	marco.setVisible(true);
     }
       
   
        
    }//GEN-LAST:event_CargarPartidaActionPerformed

    private void InformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InformacionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CargarPartida;
    private javax.swing.JButton Informacion;
    private javax.swing.JButton Jugar;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
               if(e.getSource()==Jugar) {
			FrameGeneral marco=(FrameGeneral) SwingUtilities.getWindowAncestor(this);
			marco.remove(this);
			marco.add(new MenuModo());
			marco.setVisible(true);
		}
                
                if(e.getSource()==Informacion) {
			FrameGeneral marco=(FrameGeneral) SwingUtilities.getWindowAncestor(this);
			marco.remove(this);
			marco.add(new MenuInfo());
			marco.setVisible(true);
		}
               
          
            if(e.getSource()==Salir){
            System.exit(0); 
        }
        
        
        
        
    }
}
