/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OpcionesMenu;

import menucoldware.FrameGeneral;
import InformacionPaneles.InfoJugar;
import InformacionPaneles.InfoPlanetas;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.SwingUtilities;

/**
 *
 * @author rasca
 */
public class MenuInfo extends javax.swing.JPanel implements ActionListener {

    /**
     * Creates new form InfoGeneral
     */
    public MenuInfo() {
        initComponents();
         infoDesarrolladores.addActionListener(this);
         InfoPlanetas.addActionListener(this);
         comoJugar.addActionListener(this);
         Volver.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoDesarrolladores = new javax.swing.JButton();
        InfoPlanetas = new javax.swing.JButton();
        comoJugar = new javax.swing.JButton();
        Volver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        infoDesarrolladores.setText("Desarrolladores");
        add(infoDesarrolladores, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 263, 37));

        InfoPlanetas.setText("Planetas");
        InfoPlanetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoPlanetasActionPerformed(evt);
            }
        });
        add(InfoPlanetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 124, 263, 37));

        comoJugar.setText("¿Como Jugar?");
        add(comoJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 274, 263, 34));

        Volver.setText("Volver");
        add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 660, 101, 39));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/config_equips_.gif"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 770));
    }// </editor-fold>//GEN-END:initComponents

    private void InfoPlanetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoPlanetasActionPerformed
        // TODO add your handling code here: 
    }//GEN-LAST:event_InfoPlanetasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InfoPlanetas;
    private javax.swing.JButton Volver;
    private javax.swing.JButton comoJugar;
    private javax.swing.JButton infoDesarrolladores;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        
        if(e.getSource()==InfoPlanetas){
        FrameGeneral marco=(FrameGeneral) SwingUtilities.getWindowAncestor(this);
	marco.remove(this);
	marco.add(new InfoPlanetas());
	marco.setVisible(true);
        }
         if(e.getSource()==infoDesarrolladores){
        FrameGeneral marco=(FrameGeneral) SwingUtilities.getWindowAncestor(this);
	marco.remove(this);
	marco.add(new infoDesarrolador());
	marco.setVisible(true);
        }
          if(e.getSource()==comoJugar){
        FrameGeneral marco=(FrameGeneral) SwingUtilities.getWindowAncestor(this);
	marco.remove(this);
	marco.add(new InfoJugar());
	marco.setVisible(true);
        }
        if(e.getSource()==Volver){
        FrameGeneral marco=(FrameGeneral) SwingUtilities.getWindowAncestor(this);
	marco.remove(this);
	marco.add(new MenuPrincipal());
	marco.setVisible(true);
        }
           
        
        
    }
}

