package PartidaNormal;

import OpcionesMenu.MenuModo;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import menucoldware.FrameGeneral;

/**
 *
 * @author david
 */
public class ConfigEquipos extends javax.swing.JPanel {

    //Creacion de las variables 
    int numeroEquipos;
    int contadorNumEquipos;
    Planeta crearEquipo;
    //IMPORTANT: La ArrayList se crea de nuevo cada vez que "refrescamos" el panel, encontrar una solución.
    ArrayList<Planeta> equipos = new ArrayList<Planeta>();
    
    //Vidas y misiles de cada tipo de equipo para poder mostrarlos.
    String vidasNormal = "200";
    String misilesNormal = "50";
    String vidasRojo = "200";
    String misilesRojo = "50";
    String vidasAzul = "200";
    String misilesAzul = "50";
    String vidasVerde = "200";
    String misilesVerde = "50";
    String vidasGaseoso = "400";
    String misilesGaseoso = "10";
    String vidasEnano = "100";
    String misilesEnano = "50";
    String vidasBerserk = "100";
    String misilesBerserk = "150";
    String vidasOscuro = "200";
    String misilesOscuro = "50";
    String vidasVegeta = "100";
    String misilesVegeta = "30";
    String vidasNigromante = "175";
    String misilesNigromante = "40";
    
    //Descripción de las habilidades de los planetas para poder mostrarlas.
    String skillNormal = "No tiene ninguna habilidad especial.";
    String skillRojo = "Ataques efectivos contra equipos verdes (x2). Poco efectivos contra equipos azules (/2).";
    String skillAzul = "Ataques efectivos contra equipos rojos (x2). Poco efectivos contra equipos verdes (/2).";
    String skillVerde = "Ataques efectivos contra equipos azules (x2). Poco efectivos contra equipos rojos (/2).";
    String skillGaseoso = "Gana 10 misiles máximos por ronda.";
    String skillEnano = "Tiene una probabilidad del 50% de esquivar los ataques.";
    String skillBerserk = "No puede defenderse.";
    String skillOscuro = "Inflinge el doble de daño a los objetivos con menos del 20% de su salud máxima.";
    String skillVegeta = "Obtiene +100 de vida y +10 misiles por equipo en la partida.";
    String skillNigromante = "Cuando un equipo muere, se cura 40 puntos de vida y recibe +20 misiles.";
    
    
    
    public ConfigEquipos(int numEquipos, int contNumEquipos) {
        initComponents();
            numeroEquipos = numEquipos;
            contadorNumEquipos = contNumEquipos;
            
            textNumeroEquipo.setText(String.valueOf("Equipo " + contNumEquipos));

            //Iniciamos los valores a los del equipo normal (que esta seleccionado de forma predeterminada).
            numeroVidasTipo.setText(vidasNormal);
            numeroMisilesTipo.setText(misilesNormal);
            skillTipo.setText(skillNormal);
            
            //Hacemos que seleccionar un tipo de equipo de la lista cuente como una acción para poder cambiar la información que se muestra.
            listaTipos.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    listaTiposActionPerformed(evt);
                }
            });
            
            //Añadimos un ActionListener al boton de "continuar".
            botonFinalizarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFinalizarEquipoActionPerformed(evt);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textNumeroEquipo = new javax.swing.JTextField();
        nombreEquipo = new javax.swing.JTextField();
        listaTipos = new javax.swing.JComboBox<>();
        labelVidas = new javax.swing.JLabel();
        labelMisiles = new javax.swing.JLabel();
        labelHabilidad = new javax.swing.JLabel();
        labelIntroduceNombre = new javax.swing.JLabel();
        labelEligeTipo = new javax.swing.JLabel();
        labelStatsTipo = new javax.swing.JLabel();
        numeroVidasTipo = new javax.swing.JTextField();
        numeroMisilesTipo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        skillTipo = new javax.swing.JTextArea();
        botonFinalizarEquipo = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1280, 768));

        textNumeroEquipo.setEditable(false);
        textNumeroEquipo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        textNumeroEquipo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        nombreEquipo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nombreEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreEquipoActionPerformed(evt);
            }
        });

        listaTipos.setBackground(new java.awt.Color(204, 204, 204));
        listaTipos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        listaTipos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Rojo", "Azul", "Verde", "Gaseoso", "Enano", "Berserk", "Oscuro", "Vegeta Super Saiyan 2", "Nigromante" }));
        listaTipos.setToolTipText("El tipo del equipo cambia sus estadísticas y habilidades (si tiene).");
        listaTipos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        labelVidas.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelVidas.setText("VIDAS:");

        labelMisiles.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelMisiles.setText("MISILES:");

        labelHabilidad.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelHabilidad.setText("HABILIDAD:");

        labelIntroduceNombre.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelIntroduceNombre.setText("Introduce el nombre del equipo:");

        labelEligeTipo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelEligeTipo.setText("Elige el tipo (clase) del equipo:");

        labelStatsTipo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelStatsTipo.setText("Estadísticas del tipo");

        numeroVidasTipo.setEditable(false);
        numeroVidasTipo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        numeroVidasTipo.setForeground(new java.awt.Color(0, 255, 0));
        numeroVidasTipo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numeroVidasTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroVidasTipoActionPerformed(evt);
            }
        });

        numeroMisilesTipo.setEditable(false);
        numeroMisilesTipo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        numeroMisilesTipo.setForeground(new java.awt.Color(255, 51, 51));
        numeroMisilesTipo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numeroMisilesTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroMisilesTipoActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        skillTipo.setEditable(false);
        skillTipo.setColumns(20);
        skillTipo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        skillTipo.setLineWrap(true);
        skillTipo.setRows(5);
        skillTipo.setWrapStyleWord(true);
        jScrollPane1.setViewportView(skillTipo);

        botonFinalizarEquipo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        botonFinalizarEquipo.setText("Continuar");

        botonCancelar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botonCancelar.setText("Cancelar y volver");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textNumeroEquipo)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelIntroduceNombre)
                                .addGap(13, 13, 13)
                                .addComponent(nombreEquipo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelEligeTipo)
                                .addGap(25, 25, 25)
                                .addComponent(listaTipos, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addComponent(labelStatsTipo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelVidas)
                                            .addComponent(labelMisiles))
                                        .addGap(162, 162, 162)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(numeroVidasTipo)
                                            .addComponent(numeroMisilesTipo)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelHabilidad)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 99, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonFinalizarEquipo)
                        .addGap(363, 363, 363)
                        .addComponent(botonCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textNumeroEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelIntroduceNombre)
                            .addComponent(labelStatsTipo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelVidas)
                            .addComponent(numeroVidasTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelMisiles)
                            .addComponent(numeroMisilesTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(listaTipos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelEligeTipo))
                                .addComponent(labelHabilidad))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addComponent(botonFinalizarEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nombreEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreEquipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreEquipoActionPerformed

    private void numeroVidasTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroVidasTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroVidasTipoActionPerformed

    private void numeroMisilesTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroMisilesTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroMisilesTipoActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        // TODO add your handling code here:
        FrameGeneral marco=(FrameGeneral) SwingUtilities.getWindowAncestor(this);
	marco.remove(this);
	marco.add(new EleccionNumEquipos());
	marco.setVisible(true);
    }//GEN-LAST:event_botonCancelarActionPerformed
    
    private void botonFinalizarEquipoActionPerformed(java.awt.event.ActionEvent evt) {
        //Guardamos el equipo con los parametros seleccionados por el jugador.
        boolean nombreRepe = false;
        int x;
        
        //Comprobamos que el nombre del equipo sea diferente al de los otros.
        for (x = 0; x < equipos.size(); x++) {
				if (equipos.get(x).getNombreEquipo().equals(nombreEquipo.getText())) {
                                        JOptionPane.showMessageDialog(this,"El nombre del equipo ya está en uso. Introduce un nombre único.");
                                        nombreRepe = true;
                                        System.out.println("Comprobant nom");
				}
			}
        if (nombreRepe == false){
            //Cuando el nombre no está repetido creamos el equipo y "refrescamos" el jpanel hasta que se hayan creado todos los equipos.
            crearEquipo = (new Planeta(nombreEquipo.getText(), listaTipos.getSelectedIndex()));
            equipos.add(crearEquipo);
            System.out.println(equipos.size());
            
            if (contadorNumEquipos < numeroEquipos){
                  botonFinalizarEquipo.revalidate();
                  botonFinalizarEquipo.repaint();
                  nombreEquipo.setText("");
                  listaTipos.setSelectedIndex(0);
                  contadorNumEquipos++;
                  textNumeroEquipo.setText(String.valueOf("Equipo " + contadorNumEquipos));
                  System.out.println(contadorNumEquipos);
            }else{
                //IMPORTANTE: Aqui irá el codigo a ejecutarse cuando se hayan creado todos los equipos (Por el momento te devuelve al menú de modos).
                FrameGeneral marco=(FrameGeneral) SwingUtilities.getWindowAncestor(this);
		marco.remove(this);
		marco.add(new MenuModo());
		marco.setVisible(true);
            }
        }
    }
    
    private void listaTiposActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        //Condiciones para cambiar la información mostrada dependiendo del tipo seleccionado.
        if(listaTipos.getSelectedIndex() == 0){
            numeroVidasTipo.setText(vidasNormal);
            numeroMisilesTipo.setText(misilesNormal);
            skillTipo.setText(skillNormal);
        }else if (listaTipos.getSelectedIndex() == 1){
            numeroVidasTipo.setText(vidasRojo);
            numeroMisilesTipo.setText(misilesRojo);
            skillTipo.setText(skillRojo);
        }else if (listaTipos.getSelectedIndex() == 2){
            numeroVidasTipo.setText(vidasAzul);
            numeroMisilesTipo.setText(misilesAzul);
            skillTipo.setText(skillAzul);
        }else if (listaTipos.getSelectedIndex() == 3){
            numeroVidasTipo.setText(vidasVerde);
            numeroMisilesTipo.setText(misilesVerde);
            skillTipo.setText(skillVerde);
        }else if (listaTipos.getSelectedIndex() == 4){
            numeroVidasTipo.setText(vidasGaseoso);
            numeroMisilesTipo.setText(misilesGaseoso);
            skillTipo.setText(skillGaseoso);
        }else if (listaTipos.getSelectedIndex() == 5){
            numeroVidasTipo.setText(vidasEnano);
            numeroMisilesTipo.setText(misilesEnano);
            skillTipo.setText(skillEnano);
        }else if (listaTipos.getSelectedIndex() == 6){
            numeroVidasTipo.setText(vidasBerserk);
            numeroMisilesTipo.setText(misilesBerserk);
            skillTipo.setText(skillBerserk);
        }else if (listaTipos.getSelectedIndex() == 7){
            numeroVidasTipo.setText(vidasOscuro);
            numeroMisilesTipo.setText(misilesOscuro);
            skillTipo.setText(skillOscuro);
        }else if (listaTipos.getSelectedIndex() == 8){
            numeroVidasTipo.setText(vidasVegeta);
            numeroMisilesTipo.setText(misilesVegeta);
            skillTipo.setText(skillVegeta);
        }else if (listaTipos.getSelectedIndex() == 9){
            numeroVidasTipo.setText(vidasNigromante);
            numeroMisilesTipo.setText(misilesNigromante);
            skillTipo.setText(skillNigromante);
        }
    }                 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonFinalizarEquipo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelEligeTipo;
    private javax.swing.JLabel labelHabilidad;
    private javax.swing.JLabel labelIntroduceNombre;
    private javax.swing.JLabel labelMisiles;
    private javax.swing.JLabel labelStatsTipo;
    private javax.swing.JLabel labelVidas;
    private javax.swing.JComboBox<String> listaTipos;
    private javax.swing.JTextField nombreEquipo;
    private javax.swing.JTextField numeroMisilesTipo;
    private javax.swing.JTextField numeroVidasTipo;
    private javax.swing.JTextArea skillTipo;
    private javax.swing.JTextField textNumeroEquipo;
    // End of variables declaration//GEN-END:variables
}
