package PartidaNormal;

import OpcionesMenu.MenuModo;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import menucoldware.FrameGeneral;

/**
 *
 * @author david
 */
public class EleccionNumEquipos extends javax.swing.JPanel {
    
    public EleccionNumEquipos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cuantosEquipos = new javax.swing.JLabel();
        volverMenuModo = new javax.swing.JButton();
        numEquiposUsuario = new javax.swing.JTextField();
        botonAceptarNum = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1280, 768));

        cuantosEquipos.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        cuantosEquipos.setText("¿Cuántos equipos van a jugar?");

        volverMenuModo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        volverMenuModo.setText("Volver");
        volverMenuModo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverMenuModoActionPerformed(evt);
            }
        });

        numEquiposUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numEquiposUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numEquiposUsuario.setToolTipText("");
        numEquiposUsuario.setActionCommand("<Not Set>");
        numEquiposUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        botonAceptarNum.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonAceptarNum.setText("Aceptar");
        botonAceptarNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarNumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volverMenuModo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(cuantosEquipos)
                        .addGap(0, 381, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(595, 595, 595)
                        .addComponent(botonAceptarNum))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(566, 566, 566)
                        .addComponent(numEquiposUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(cuantosEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(numEquiposUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonAceptarNum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 271, Short.MAX_VALUE)
                .addComponent(volverMenuModo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void volverMenuModoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverMenuModoActionPerformed
        // TODO add your handling code here:
        FrameGeneral marco=(FrameGeneral) SwingUtilities.getWindowAncestor(this);
        marco.remove(this);
        marco.add(new MenuModo());
        marco.setVisible(true);
    }//GEN-LAST:event_volverMenuModoActionPerformed

    private void botonAceptarNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarNumActionPerformed
        // TODO add your handling code here:
        try{
            //Solo aceptaremos numeros.
            int numEquipos = Integer.parseInt(numEquiposUsuario.getText());

            if(numEquipos >= 3){
                FrameGeneral marco=(FrameGeneral) SwingUtilities.getWindowAncestor(this);
                marco.remove(this);
                marco.add(new ConfigEquipos(numEquipos, 1));
                marco.setVisible(true);
            }else if(numEquipos < 3){
                JOptionPane.showMessageDialog(this,"El modo normal de COLDWAR requiere un mínimo de 3 equipos");
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"¡Debes introducir un numero! (Y que no sea enorme)");
        }
    }//GEN-LAST:event_botonAceptarNumActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptarNum;
    private javax.swing.JLabel cuantosEquipos;
    private javax.swing.JTextField numEquiposUsuario;
    private javax.swing.JButton volverMenuModo;
    // End of variables declaration//GEN-END:variables
}
