package PartidaNormal;

import OpcionesMenu.MenuModo;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import menucoldware.FrameGeneral;

/**
 *
 * @author david
 */
public class EleccionNumEquipos extends javax.swing.JPanel {
    
    public EleccionNumEquipos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cuantosEquipos = new javax.swing.JLabel();
        volverMenuModo = new javax.swing.JButton();
        numEquiposUsuario = new javax.swing.JTextField();
        botonAceptarNum = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1280, 768));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cuantosEquipos.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        cuantosEquipos.setForeground(new java.awt.Color(255, 255, 255));
        cuantosEquipos.setText("¿Cuántos equipos van a jugar?");
        add(cuantosEquipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 208, -1, 64));

        volverMenuModo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        volverMenuModo.setText("Volver");
        volverMenuModo.setFocusable(false);
        volverMenuModo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverMenuModoActionPerformed(evt);
            }
        });
        add(volverMenuModo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 680, 100, 40));

        numEquiposUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numEquiposUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numEquiposUsuario.setToolTipText("");
        numEquiposUsuario.setActionCommand("<Not Set>");
        numEquiposUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        add(numEquiposUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(566, 336, 149, 68));

        botonAceptarNum.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonAceptarNum.setText("Aceptar");
        botonAceptarNum.setFocusable(false);
        botonAceptarNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarNumActionPerformed(evt);
            }
        });
        add(botonAceptarNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 416, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/config_equips_.gif"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 760));
    }// </editor-fold>//GEN-END:initComponents

    private void volverMenuModoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverMenuModoActionPerformed
        // TODO add your handling code here:
        FrameGeneral marco=(FrameGeneral) SwingUtilities.getWindowAncestor(this);
        marco.remove(this);
        marco.add(new MenuModo());
        marco.setVisible(true);
    }//GEN-LAST:event_volverMenuModoActionPerformed

    private void botonAceptarNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarNumActionPerformed
        // TODO add your handling code here:
        try{
            //Solo aceptaremos numeros.
            int numEquipos = Integer.parseInt(numEquiposUsuario.getText());

            if(numEquipos >= 3){
                FrameGeneral marco=(FrameGeneral) SwingUtilities.getWindowAncestor(this);
                marco.remove(this);
                marco.add(new ConfigEquipos(numEquipos, 1));
                marco.setVisible(true);
            }else if(numEquipos < 3){
                JOptionPane.showMessageDialog(this,"El modo normal de COLDWAR requiere un mínimo de 3 equipos");
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"¡Debes introducir un numero! (Y que no sea enorme)");
        }
    }//GEN-LAST:event_botonAceptarNumActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptarNum;
    private javax.swing.JLabel cuantosEquipos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField numEquiposUsuario;
    private javax.swing.JButton volverMenuModo;
    // End of variables declaration//GEN-END:variables
}
