/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BossRush;

import OpcionesMenu.MenuModo;
import BossRush.PanelBossRush;
import menucoldware.FrameGeneral;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import menucoldware.FrameGeneral;

/**
 *
 * @author sergipaz
 */
public class Nombre_Boss_Rush extends javax.swing.JPanel {

    /**
     * Creates new form Nombre_Usuario_BRush
     */
    public Nombre_Boss_Rush() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Boton_Nombre = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1280, 768));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Boton_Nombre.setText("Jugar");
        Boton_Nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_NombreMouseClicked(evt);
            }
        });
        Boton_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_NombreActionPerformed(evt);
            }
        });
        add(Boton_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 660, 145, 39));

        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 100, 40));

        Nombre.setText("Nombre");
        add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, 218, 54));

        jLabel2.setFont(new java.awt.Font(".SF NS Text", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Tip* : Recomendamos ver el tutorial antes de jugar");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, 360, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Inserte su nombre");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 240, 46));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/descansi.gif"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_NombreActionPerformed
        // TODO add your handling code here:

        String Nombre_Usuario = "" + Nombre.getText();

        //JOptionPane.showMessageDialog(this, "Hola, "+ Nombre_Usuario);

        FrameGeneral marco=(FrameGeneral) SwingUtilities.getWindowAncestor(this);
        marco.remove(this);
        marco.add(new PanelBossRush(Nombre_Usuario));
        marco.setVisible(true);
    }//GEN-LAST:event_Boton_NombreActionPerformed

    private void Boton_NombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_NombreMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_NombreMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FrameGeneral marco=(FrameGeneral) SwingUtilities.getWindowAncestor(this);
        marco.remove(this);
        marco.add(new MenuModo());
        marco.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Nombre;
    private javax.swing.JTextField Nombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
